### ISSUE TITLE
 "webpack": "5.4.0",     "webpack-cli": "^4.0.0-rc.0",

### ISSUE THREAD

**Issue by thisVioletHydra** [wenhongjie/webpack-progress-bar#4]
```
[webpack-cli] Compilationdevelopment starting...
                           0% 0.0s[webpack-cli] TypeError: Cannot read property 'intercept' of undefined
    at C:\FRONTEND\www\group-dashboard\group-dashboard-postman\node_modules\webpack-progress-bar\node_modules\webpack\lib\ProgressPlugin.js:242:30
    at Array.forEach (<anonymous>)
    at C:\FRONTEND\www\group-dashboard\group-dashboard-postman\node_modules\webpack-progress-bar\node_modules\webpack\lib\ProgressPlugin.js:239:24
    at Hook.eval [as call] (eval at create (C:\FRONTEND\www\group-dashboard\group-dashboard-postman\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:102:1)
    at Hook.CALL_DELEGATE [as _call] (C:\FRONTEND\www\group-dashboard\group-dashboard-postman\node
```

**Comment by thisVioletHydra** [comment]
RIP 👩🏾‍🦽🚑
